-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module SkelLE where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified AbsLE

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transExp :: AbsLE.Exp -> Result
transExp x = case x of
  AbsLE.EAdd exp1 exp2 -> failure x
  AbsLE.ESub exp1 exp2 -> failure x
  AbsLE.EMul exp1 exp2 -> failure x
  AbsLE.EDiv exp1 exp2 -> failure x
  AbsLE.EInt integer -> failure x
